"""empty message

Revision ID: 03df0a657424
Revises: 
Create Date: 2024-06-04 10:58:05.008474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03df0a657424'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usertable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blogtable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['usertable.id'], name=op.f('fk_blogtable_userid_usertable')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blogtable')
    op.drop_table('usertable')
    # ### end Alembic commands ###
